Element C:
    formula: C
    number: 6
    period: 2
    group: 14
    bonds:
        - formula: O
          bond length: 1.142

Element O:
    formula: O
    number: 8
    period: 2
    group: 16
    bonds:
        - formula: C
          bond length: 1.142

        - formula: Ce
          bond length: 2.356

Element Ce:
    formula: Ce
    number: 58
    period: 6
    group: 3
    bonds:
        - formula: O
          bond length: 2.356
